### ISSUE TITLE
Create Helm Chart for easy deployment of Configurator

### ISSUE THREAD

**Issue by gopaddle-io** [gopaddle-io/configurator#16]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create a Helm chart for easy deployment of Configurator.

**Describe alternatives you've considered**
Currently Configurator is installed through a sequence of YAML files. Instead, create a simple helm chart the does a single command install of configurator.

**Additional context**
None

**Comment by juliohm1978** [comment]
I believe this has been addressed by https://github.com/gopaddle-io/configurator/pull/41.

**Comment by gopaddle-io** [comment]
New Helm version created for v0.0.2
