### ISSUE TITLE
Modify makefile so that we dont push the docker image to docker hub everytime we build

### ISSUE THREAD

**Issue by gopaddle-io** [gopaddle-io/configurator#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Take the docker registry parameter as an input to make file and push the image to the user defined registry rather than using the Bluemeric docker registry. We need to have qualification process before pushing the image to Bluemeric docker registry. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by logeshkrish** [comment]
seperate push command added
