### ISSUE TITLE
Use commonly used based image while building the Docker image for configurator

### ISSUE THREAD

**Issue by gopaddle-io** [gopaddle-io/configurator#21]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use a more commonly used base image instead of bluemeric/golang. Modify Dockerfile to include the steps for setting up golang ENVs

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by logeshkrish** [comment]
common image golang replaced
