### ISSUE TITLE
Rollback breaks the ConfigMap labels in deployments

### ISSUE THREAD

**Issue by renugadevi-2613** [gopaddle-io/configurator#30]
**Describe the bug**
if we once rollback the changes in deployment. Deployment labels and configmaps are still pointing to old labels. This is breaking the rollback functionality.

**To Reproduce**
1. deploy configurator
2. create customConfigMap
3. copy the newly created configMapName and add it in the deployment label and volume
4. change the customConfigMap configurator create new configMap update the deployment.
5. rollback to the previous revision of the deployment. it pointing to the first version of deployment.
6. change the customConfigMap it create new configMap but the rolling update did not worked.

**Screenshots**
None

**Comment by juliohm1978** [comment]
Hi.

I believe this is the point where the controller gets confused about which Deploy/Sts should be updated.

https://github.com/gopaddle-io/configurator/blob/8e78843e20b83a8d740f67f852d642f81ebe0ed1/watcher/watcher.go#L57

Deploy/Sts are listed with a label selector that match the current latest CM name, which is the the CM newly created before calling `StartWatcher()`.

One thing that comes to mind here is the necessity to include the latest CM name in the label selector. Once the original CCM was modified, maybe all Deploy/Sts that use CMs managed by that CCM should be updated, regardless of which CM version they are using at the moment. Does that make any sense.

There are several ways to change this behavior.

The easiest would be to patch Deploy/Sts with a label that indicates which CCM is managing the CM on that object. But this can cause issues if you have multiple CCMs managing various CMs in the same Deploy/Sts.

Maybe the label could be considered a multi-valued field, with a list of all CCMs separated by commas?

**Comment by renugadevi-2613** [comment]
I can see how this can get more complex when multiple configMaps are used in a deployment. We can decide a fix for this issue considering the suggestions under issue #34 as well. We need to arrive at a better strategy to keep track of configMap changes that works in gitOps, argoCD workflow as well.

**Comment by gopaddle-io** [comment]
Fixed in v0.0.2
