### ISSUE TITLE
Website: Include Contributor list on Configurator home page

### ISSUE THREAD

**Issue by Adeesh-devanand** [gopaddle-io/configurator#48]
I tried including the list of Contributors on the Configurator home page but got stuck. If anyone has any experience using Github API's or JavaSctipt, the help would be much appreciated. 

This is what I'hve reached at so far:
```
<script type="module"> 
import { Octokit } from "https://cdn.skypack.dev/@octokit/core"; 
const octokit = new Octokit(); 
await octokit.request('GET /repos/gopaddle-io/configurator/stats/contributors', { owner: 'gopaddle-io', repo: 'configurator' }).then((resp) => { resp.data.forEach((r) => { console.log(r.author.login); }) });
</script>
```
I'm guessing that the GET call is working all right but how do I take the data and display it.

Here's the link to the [code](https://github.com/gopaddle-io/configurator/blob/main/docs/_pages/home.md) if you can fix it.

Here's the link to the [Home page](https://gopaddle-io.github.io/configurator/)

I wanted to display the contributor list under "Thanks to all contributors for their effort"

![Screenshot 2021-10-06 201429](https://user-images.githubusercontent.com/81635340/136231848-7357d1ae-de6e-4864-ad5f-150e573c364f.png)

Thank you for your help!!

PS: I'm not really a web developer or JS practioner.

**Comment by VaithiSniper** [comment]
I would like to take this up. Can you be more specific about what you want? Do you want to display avatars of users who've contributed there? And why discord APIs (I do have experience in that btw)

**Comment by Adeesh-devanand** [comment]
Hey, sorry about that I meant to say github API's instead of Discord API's. (I have edited the comment)

I have made a rough sketch of what I was going for here ...

![Screenshot 2022-03-11 120816](https://user-images.githubusercontent.com/81635340/157816677-49986fff-e1d9-4731-abdf-49970acd8106.png)

If you could get the contributors' avatars and names from the github API and get it to display them as so, it would be great!!

**Comment by VaithiSniper** [comment]
> Hey, sorry about that I meant to say github API's instead of Discord API's. (I have edited the comment)
> 
> I have made a rough sketch of what I was going for here ...
> 
> ![Screenshot 2022-03-11 120816](https://user-images.githubusercontent.com/81635340/157816677-49986fff-e1d9-4731-abdf-49970acd8106.png)
> 
> If you could get the contributors' avatars and names from the github API and get it to display them as so, it would be great!!

I'd love to work on this! Just one question, will it be counted towards sodacode?

**Comment by gopaddle-io** [comment]
Yes, this issue is tagged for SODACODE.

**Comment by VaithiSniper** [comment]
Hey, I've got the avatars and the names working. Which branch on the main repo do I issue the PR to?

**Comment by Adeesh-devanand** [comment]
Hi, you can send a PR to SODACODE-2022 branch.

**Comment by VaithiSniper** [comment]
I've sent a PR, can you check and merge it if fine?
