### ISSUE TITLE
Automate weekly updates

### ISSUE THREAD

**Issue by Adeesh-devanand** [gopaddle-io/configurator#52]
Require automation for uploading weekly meetings to the Configurator website:

Anyone with experience automating file updation on GitHub could help out.

**Probelm statement:**
Look for changes on request in a YouTube playlist and send a pull request after adding and changing a specific file.

Issue is open to any newcomers who are willing to explore the GitHub API and try out some JavaScript.

Join the Discord Server for a detailed explanation.

**Comment by gopaddle-io** [comment]
Please send pull requests to SODACODE-2022
