### ISSUE TITLE
At the time git push, newly edited contents and a few files under helm-src folder are  ignored

### ISSUE THREAD

**Issue by surendar-b** [gopaddle-io/configurator#84]
**Describe the bug**
Push helm-src code to the git repository. It ignores few files and newly edited contents.
**To Reproduce**
1.Add all your local changes
```sh
$ git add .
```
2.Commit all changes using git commit
```sh
$ git commit -m <comment description>
```
3.push the code to the git repository using the git push. 
```sh
$ git push origin v0.0.2
```

**Comment by gopaddle-io** [comment]
Fixed in v0.0.2
