### ISSUE TITLE
 Move the purge functionality to a kube job

### ISSUE THREAD

**Issue by surendar-b** [gopaddle-io/configurator#87]
**Describe the bug**
     Cleaning up unused customConfigMap/customSecret from the cluster. Purge functionality will do the cleaning every 15 mins. Now the purge process is part of the configurator code.
**Expected behavior**
   Move the purge process as a separate one and create the kubernetes job resource to clean the CCM/CS every 15 mins.

**Comment by gopaddle-io** [comment]
Please send pull requests to SODACODE-2022
